"""Initial migration

Revision ID: 0e82b14be364
Revises: 
Create Date: 2026-02-23 19:57:00.259693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e82b14be364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'deactivated', name='company_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('client_portal', sa.Boolean(), nullable=True),
    sa.Column('bookings', sa.Boolean(), nullable=True),
    sa.Column('invoicing', sa.Boolean(), nullable=True),
    sa.Column('inventory', sa.Boolean(), nullable=True),
    sa.Column('team_onboarding', sa.Boolean(), nullable=True),
    sa.Column('field_reports', sa.Boolean(), nullable=True),
    sa.Column('surveys', sa.Boolean(), nullable=True),
    sa.Column('social_scheduler', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('owner', 'admin', 'manager', 'staff', 'field_worker', 'receptionist', 'accountant', 'viewer', name='user_roles'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'suspended', 'deactivated', name='user_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
