"""Add social media models

Revision ID: 9833409bf14b
Revises: e3cfaf5a1032
Create Date: 2026-02-23 20:00:35.472617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9833409bf14b'
down_revision = 'e3cfaf5a1032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.Enum('facebook', 'instagram', 'twitter', 'linkedin', name='platform_types'), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'posted', 'failed', name='post_status'), nullable=True),
    sa.Column('platform_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_posts')
    op.drop_table('social_platforms')
    # ### end Alembic commands ###
